name: Deploy Airflow DAG

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
    paths:
      - "dags/script.py"  # Only trigger when script.py is updated

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runner
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Set up SSH keys for EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Store private SSH key as a secret
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts  # Use the secret for public IP
      
      - name: Debug file paths
        run: ls -R

      - name: Copy script.py to EC2 instance
        run: |
          scp -i ~/.ssh/id_rsa dags/script.py ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/airflow/dags/script.py  # Use the secret for public IP